uber/tchannel-node

- peer.js
- peers_base.js
- root_peers.js
- sub_peers.js
- test/peer_strategies.js
r @jcorbin @Raynos @kriskowal 
cc @anson627
From https://github.com/uber/tchannel/pull/1348
> subChannel should be able to set peer preference

- errors.js
- operations.js
- peer.js
- test/lib/alloc-cluster.js
- test/lib/batch-client.js
- test/lib/collapsed-assert.js
- test/pool-of-servers.js
This allows a peer to favor non-busy peers.
r: @jcorbin @rf @shannili
> Take busy frames into account for peer selection

- connection.js
- v2/handler.js
- v2/out_response.js
> v2/handler: decouple #sendErrorFrame from req/res

- peer.js
- peers_base.js
Add peer log extension
r @kriskowal, @Raynos
> TChannelPeer{,sBase}: add #extendLogInfo for completeness

- operations.js
> Fix references to pending.errors

- hyperbahn-client.js
Resend the reverted change and see if tests are passing.
@jcorbin
> Resend unadvertise should drain

- v2/handler.js
> Eliminate a per req/res closure allocation in v2/handler

- as/http.js
> as/http: refactor headerPairs get/set onto its object

- connection.js
Another step towards #15 
r @Raynos @rf
> Only reset connection for null-id'd protocol errors

- Makefile
There is a bunch of multi repo cruft in the codebase.
r: @kriskowal @jcorbin @rf
> remove cruft from Makefile

- test/v2/lazy_frame.js
- v2/error_response.js
> v2/error_response: lazy error reading

- errors.js
- test/errors.js
> test/errors: enforce code classification coverage

- as/thrift.js
- hyperbahn-client.js
- test/as-thrift.js
- test/hyperbahn-client/constructor.js
- test/hyperbahn-client/thrift-codec.js
- test/index.js
In passing when trying to upgrade tchannel-gen to
tchannel@3 I want to make some user interface improvements
There are a bunch of changes in this PR and some are more
"debatable" then others.
I will break anything contraversial into a seperate PR.
> TChannelThrift UX improvements

- connection.js
- relay_handler.js
- test/relay_lazy.js
With tests to demonstrate the stack traces reported in #29.
> Fix bugs in lazy relaying

- channel.js
- connection.js
- lib/stat.js
- lib/statsd.js
- out_request.js
- out_response.js
- peer.js
- relay_handler.js
- request.js
- test/connection-stats.js
- test/request-stats.js
- test/response-stats.js
> Finish the fast stats conversion

- out_request.js
- request.js
> Decouple Request Stat Emission

- test/v2/lazy_frame.js
- v2/call.js
Never worked, viva la test coverage.
> Test and fix v2.CallResponse.RW.lazy.readArg1

- hyperbahn-client.js
- test/hyperbahn-client/thrift-codec.js
r @Raynos @kriskowal 
ref: #46
> only implement Meta::thriftIDL when the thriftFileName is provided

- test/v2/lazy_frame.js
- v2/call.js
- v2/header.js
> Update lazy arg1 reader to optionally re-use lazily read header information

- relay_handler.js
> LazyRelayInReq: read and carry headers and endpoint

- relay_handler.js
> Fix typo and carry channel on lazy reqs

- test/lib/simple_validators.js
- test/relay-stats.js
- reduce order sensitivity
- provide better test case description (full key path)
- harden against undefined values
- lint comply quoting
- factor out validate1 for future extensibility
r @Raynos @rf
> Better relay stats test

- connection.js
- relay_handler.js
- test/relay-stats.js
> Add Lazy Relay Stats

- in_request.js
- out_response.js
- relay_handler.js
Here we manually call into the circuit hooks in the
right places (tm) for go fast and less closures.
See buddy PR because `npm link` and code organization :(
https://github.com/uber/hyperbahn/pull/38
> Implement new circuit hooks

- benchmarks/bench_server.js
- benchmarks/index.js
- benchmarks/multi_bench.js
- benchmarks/relay_server.js
- connection.js
> Fix tchan benchmark + remove hardcoded numbers

- channel.js
@jcorbin 
Did I understand the things right this time
> default useLazyHandling to false

- package.json
> Uprev ThriftRW to 2.3.0

- test/index.js
- test/large-send.js
- v2/args.js
r @jwolski @Raynos @kriskowal 
cc: @jcorbin 
ref: https://github.com/uber/ringpop-node/pull/200
> multi-frame send should support non-English characters

- .travis.yml
- test/config/with_lazy_relay.json
- test/config/with_peer_heap.json
- test/config/without_lazy_relay.json
- test/config/without_peer_heap.json
- test/lib/alloc-cluster.js
- test/lib/load_config.js
This allows test runs such as:
```
$ TCHANNEL_TEST_CONFIG='test/config/with_lazy_relay.json' node test
$ TCHANNEL_TEST_CONFIG='test/config/{with_lazy_relay,with_peer_heap}.json' node test
```
etc.
cc @rf 
r: @Raynos
> More flexible test config

- out_response.js
- request-handler.js
r @Raynos @kriskowal 
FYI. this is for debugging the issue of ResponseAlreadyDone & streaming related memory leaks.
> more stats to debug & handle the responseAlreadyDone issue

- lib/stat.js
I need re-learn javascript.
r: @Raynos @ShanniLi
> Fix as-http stat key

- relay_handler.js
We have a race condition where we get a CallRequestCont frame before
we finish the init req/res handshake.
This used through an uncaught about `self.outreq.conn` being undefined
because waitForIdentified() had not finished yet.
Now we have an unbounded list of ContFrames for the id and we flush
the list either when we've flushed the CallRequest or when we call
InReq.onError()
> implement init req/res blocking for lazy relay

- test/pool-of-servers.js
> Improve server pool test

- package.json
r @jcorbin cc @malandrew @blampe
> ThriftRW v2.4.0

- docs/GUIDE.md
The main guide had some broken links. I fixed them.
> Fixed broken links

- time_heap.js
> Prevent reentry to drainExpired loop

- relay_handler.js
- test/lib/collapsed-assert.js
- test/relay_lazy.js
Fix CollapsedAssert and the problems masked by it
r @Raynos
> Fix CollapsedAssert and co

- test/pool-of-servers.js
Isomorphic prep work ahead of several other PRs to ease review by lessening churn; the test passing is its own review.
> test/pool-of-servers: factor out test setup

- relay_handler.js
> Downgrade relay peer unavailable log to info

- connection_base.js
- test/relay_lazy.js
> Fix the "mismatched conn.onReqDone" warn spam

- package.json
> Uprev ThriftRW 2.5.0

- benchmarks/multi_bench.js
> FIx multi_bench so that it fails fast rather than hanging

- benchmarks/index.js
- benchmarks/multi_bench.js
> fix benchmarks to exit on client failure

- channel.js
> channel: no sweep after destroy

- package.json
> Drop unused lru-cache

- peer.js
- peer_heap.js
- sub_peers.js
per @jcorbin discuss @Raynos @ShanniLi
> Peers have a scoring strategy, not a handler

- package.json
> Upgrade thriftrw to v2.5.2

- errors.js
- peer.js
- test/peer_drain.js
> Add timeout support to peer drain

- .travis.yml
- channel.js
- test/config/with_write_buffer_ephemeral.json
- test/config/with_write_buffer_static.json
- v2/handler.js
> Add writeBuffer mode: ephemeral vs static

- out_request.js
- request.js
r @jcorbin @Raynos 
Going to look at in req in a different PR.
> Remove arg2 arg3 from out req

- .travis.yml
- channel.js
- test/config/with_write_buffer_ephemeral.json
- test/config/with_write_buffer_static.json
- v2/handler.js
Turns out that this feature made performance worse. I'm going
to remove this code right now rather then leave it around for
a while.
> Revert "Merge pull request #124 from uber/write_buffer"

- operations.js
This is support work that both #79 and #97 will need.
Open questions:
- it's currently an untested code path in this PR, but as you can see I have two upcoming tested code paths that use it... still should I unit test this feature?
> Operations: add pending change event

- peer.js
Out of #97, some cleanups, and hooking up the event added by #98.
r @rf
> Hookup pending change event to invalidate peer score

- out_request.js
Looks like there was a bad copy pasta.
> correct stat typo

- operations.js
- peers_base.js
r @Raynos @jcorbin @kriskowal 
Smears Operations#sanitySweep
> operations: smear the ops portion of sanity sweep

- peer.js
- test/peer.js
Maybe I should have written a test...
> its called ops, not operations

- peer.js
> Peer#pendingWeightedRandom: fix range

- package.json
- scripts/check_unique_test_names.sh
- test/as-json.js
- test/busy.js
- test/connection-with-statsd.js
- test/non-zero-ttl.js
- test/relay_lazy.js
- test/v2/init.js
By having unique test strings we can `git grep` for
failing tests and get exactly one match.
r: @kriskowal @jcorbin
> Verify that all test strings are unique.

- package.json
- scripts/check_files.sh
- scripts/no_only.sh
- test/chan_drain.js
I've finally had enough of flaps.
> Improve draining test for less flaps.

- peer.js
- peer_heap.js
- peer_score_strategies.js
- range.js
- sub_peers.js
~~Currently breaks pool-of-servers because it expects perfect distribution.~~
> Peer/Score strategies: ranges all the way down

- peer.js
r @jcorbin @Raynos 
Caches ranges on the peer object.
Ranges, no caching: https://people.uberinternal.com/~rf/ranges.svg
cached: https://people.uberinternal.com/~rf/range-cache.svg
> Peer: cache score ranges

- time_heap.js
> Fix time heap drain

- drain.js
- peer.js
> Reify TChannelPeer.drain* => PeerDrain

- test/peer_drain.js
This test is annoying. All these drain tests are annoying
> rewrite the test to be less flappppppppy

- v2/handler.js
Implements https://github.com/uber/tchannel/pull/1398 
r @Raynos @kriskowal @rf 
cc @ShanniLi @breerly @prashantv
> v2/handler: implement tchannel version init headers

- publish.sh
Copied progress from https://github.com/uber/hyperbahn/pull/124
> Fix publish.sh for detached HEAD

- .eslintignore
- trace/agent.js
- trace/span.js
> eslint trace/ folder

- channel.js
- sub_peers.js
> setChoosePeerWithHeap method on channel and peers

- channel.js
- lazy_relay.js
- relay_handler.js
Added a method to control the thing.
> Allow changing maximum relay ttl using flipr

- test/lib/batch-client.js
- test/pool-of-servers.js
This improves the BatchClient to be more like the one
in hyperbahn itself.
This is a cleanup ahead of the tests for timeouts.
I need to make some tests for the suspected leak and 
for the lack of double timeout conn close.
> test: BatchClient grows up to do real batching

- benchmarks/d8_peer_heap.js
- benchmarks/peer_heap.js
The peer heap benchmarks I used to make it fast. One is for running in d8, and one uses the peer heap module directly.
> peer heap benchmarks

- .eslintignore
- benchmarks/d8_peer_heap.js
- benchmarks/peer_heap.js
- peer_heap.js
More peer heap opt. This made my benchmark take half as long.
r @Raynos
> PeerHeap: cache maxRangeStart

- bin/adhoc.js
This makes this program more useful because you can
listen to 127.0.0.1 if you want.
> allow passing host from CLI

- test/index.js
- test/lib/batch-client.js
- test/relay-under-timeouts.js
- time_heap.js
The time heap fix I made was important. I added some
failing tests that require a time heap fix.
I dont know why we leaked memory; maybe it was the
uncaught instead of the time heap change...
Let's roll forward with this change.
> Adding back deferred reaping in time-heap + tests.

- lazy_relay.js
- test/relay-under-timeouts.js
I found it! It was hard to find because all of our servers
send timeout error frames for timed out in requests.
> Fix lazy out request memory leak

- drain.js
- peer.js
> Add reason to `Peer#clearDrain` / `PeerDrain#stop`

- as/json.js
Fixes #201.
r @kriskowal
cc @prashantv
> TChannelJSON: fix logger lazy grab under #send

- errors.js
- v2/handler.js
> Check init host port strings

- benchmarks/index.js
- support changing torch command
- supprot changing number of instances
> Improve benchmark running

- lib/lcg.js
Remaining uses are in example and benchmark code.
FIxes #212
> Add a note to not use the LCG in real code

- errors.js
> Reclassify tchannel.socket.write-full as a NetworkError

- package.json
> Reduce benchmark concurrency for passing tests on thin machines

- as/thrift.js
- docs/GUIDE.md
- docs/as-thrift.md
- examples/as-thrift.js
- examples/keyvalue/client.js
- examples/keyvalue/keyvalue.thrift
- examples/keyvalue/server.js
- hyperbahn-client.js
- tcollector/reporter.js
- test/as-thrift.js
- test/health.js
> Defer to ThriftRW to assert source/entryPoint option pattern

- benchmarks/bench_server.js
- benchmarks/index.js
- benchmarks/multi_bench.js
- benchmarks/read-bench-config.js
- benchmarks/relay_server.js
This will allow us to unify such things as remote config, command lines,
torching, taking, etc in Hyperbahn.  I'll be revving on the Makefile in
hyperbahn first, and then backing out results to tchannel.
> Factor out a benchmarks config module

- channel.js
> Add TChannel#setPreferConnectionDirection

- connection.js
- in_request.js
- out_request.js
> Add remoteAddr error context

- in_request.js
- relay_handler.js
> Ensure that we log any relay in req timeouts

- test/lib/collapsed-assert.js
> CollapsedAssert: moar things (sync from hyperbahn)

- connection_base.js
- in_request.js
- operations.js
- out_request.js
- test/double-response.js
> Some logging improvements around request handling

- scripts/changelog_halp.sh
This script fills in new CHANGELOG.md lines ready for editorial review.
r @kriskowal
> Add scripts/changelog_halp.sh

- lazy_relay.js
- peer.js
> More logging consistency around lazy handling

- connection.js
- lazy_relay.js
- operations.js
- self_out_request.js
- self_out_response.js
> Fix lazy relay peer score invalidation

- publish.sh
If the CHANGELOG has `vNEXT` as its last version, update it to the newly cut
version, and amend the fresh commit/tag to reflect.
> Support publishing with new CHANGELOG version

- CHANGELOG.md
> Update the changelog for upcoming release

- benchmarks/index.js
- test/connection-stats.js
- test/connection-with-statsd.js
- test/regression-listening-on-used-port.js
- test/safe-quit.js
> Stop using "localhost" ip string in tests and benchmarks

- connection.js
- v2/handler.js
Need these init headers to reason about what the other
side of the connection even is.
r: @jcorbin @rf @shannili @kriskowal
> Expose more init headers for debugging

- in_request.js
- in_response.js
- v2/handler.js
This allows people to introspect the InRequest or InResponse.
> expose call flags on in_req & in_res

- channel.js
- errors.js
- package.json
- peer.js
> Classify and downgrade bufrw connection errors

- connection.js
- self_out_response.js
- test/busy.js
- test/relay-kills-socket-after-timeouts.js
- test/send.js
- v2/error_response.js
> Lite Errors Redux

- package.json
Addressing issue with include + extends
> Upgrade thriftrw to v3.0.3

- .eslintignore
- v2/args.js
- v2/call.js
- v2/checksum.js
- v2/cont.js
- v2/error_response.js
- v2/frame.js
- v2/handler.js
- v2/header.js
- v2/index.js
- v2/init.js
- v2/out_response.js
- v2/tracing.js
I excepted curly rather than yet more churn.
r @raynos @kriskowal
> Bring v2/*.js into eslint compliance

- v2/args.js
- v2/call.js
- v2/cancel.js
- v2/checksum.js
- v2/claim.js
- v2/cont.js
- v2/error_response.js
- v2/frame.js
- v2/handler.js
- v2/header.js
- v2/init.js
- v2/lazy_frame.js
- v2/out_request.js
- v2/out_response.js
- v2/ping.js
- v2/tracing.js
> Drop use of `var self` from v2/*.js

- as/thrift.js
- package.json
- test/as-thrift.js
@kriskowal Fixes #249 
Depends on https://github.com/uber/thriftrw-node/pull/101
> Expose getServiceEndpoints from tchannelAsThrift

- as/thrift.js
> Remove overzealous err is Error check from AsThrift

- as/json.js
> Drop error O(pinions) from as/json

- service-name-handler.js
- test/busy.js
> Ensure that isBusy() bails and does not call handler

- host-port.js
> Add more useful information to host port validation

- package.json
- test/v2/args.js
- v2/args.js
> Use lazy buffer slices for arg buffer reading

- benchmarks/micro/reading-all-important-fields.js
- benchmarks/micro/reading-arg1-str.js
- test/v2/lazy_frame.js
- v2/call.js
- v2/checksum.js
- v2/lazy_frame.js
This is the third & final method to allow reading of
arg1 efficiently.
Going to add benchmarks whilst waiting for reviews.
> add cached readArg1Str()

- benchmarks/micro/reading-tracing-value.js
- errors.js
- lazy_relay.js
- test/v2/lazy_frame.js
- v2/call.js
- v2/lazy_frame.js
Faster tracing is 3x faster.
- Use the faster versions
- Also faster ttl
- Also faster tracing
> Finally use the faster versions

- lazy_relay.js
- relay_handler.js
- v2/lazy_frame.js
This PR removes some circuit breaking from tchannel that
is now upstream in hyperbahn.
See hyperbahn PR: https://github.com/uber/hyperbahn/pull/215
r: @kriskowal @rf
> Circuit breaking cleanup

- v2/lazy_frame.js
We have gotten trolled multiple times by this
uncaught.
r: @rf @jcorbin
> v2/lazy_frame: avoid out of bounds reads

- in_response.js
- out_request.js
- out_response.js
- v2/handler.js
To get more data on an edge case @uber/ringpop team is seeing.
cc @raynos
> Improve req/res log augmentation

- trace/agent.js
Previously we assumed that there was only ever one flag.
This is not future proof.
> trace: do a proper bit flag check

- lazy_relay.js
- test/relay-stats.js
Previously we only emitted inbound stats for requests that
we forward or error frames that we forward.
Now we do observability earlier and in more places to ensure
that we observe all inbound frames and all outbound error
frames.
> lazy_relay: emit inbound stats for errorFrame path

- connection.js
- v2/handler.js
- v2/lazy_frame.js
Another piece of work towards complete visibility
around error frames.
> connection: emit stats when sending error frame

- package.json
> Bump thriftrw to 3.3.0

- channel.js
- lazy_relay.js
- lib/object_pool.js
- relay_handler.js
- test/index.js
- test/object_pool.js
Inspired by Josh's PR, I tried to take a minimal stab at object pooling. This just pools `LazyRelay{In,Out}Req` objects. My pooling implementation also submits stats for all pools.
~~There's still some misplaced frees right now causing test failures, so I need to slog on this a little more to get it right.~~
This now passes all tests.
r @Raynos @jcorbin @kriskowal
> `LazyRelay{In,Out}Req` Pooling

- as/http.js
This caused an uncaught exception.
cc: @Raynos
> fix "fromo" typo in ashttp

- package.json
This fixes a bug with lists of lists in binary encode/decode
in thriftrw
> upgrade thriftrw@3.4.1

- package.json
This brings our versions of bufrw and thriftrw into alignment, fixing the underlying problem with SeriesRW, which broke lists of lists.
r @jcorbin @Raynos
> Upgrade thriftrw and bufrw

- package.json
> Upgrade thriftrw to version 3.4.3

- CHANGELOG.md
> Changelog 3.6.24

- channel.js
- sub_peers.js
- test/peer-to-peer-load-balance.js
> Oops: fix lolbug

- channel.js
- lib/rate_counter.js
- lib/retry_ratio_tracker.js
- request.js
- test/index.js
- test/rate_counter.js
- test/retry.js
@Raynos @syyang @hanjunx @charliezhang PTAL
> support per-client retry budget to avoid excessive retries overwhelming server

- as/thrift.js
- test/as-thrift.js
> add option to pass pre-compiled thrift spec

- as/thrift.js
- package.json
- test/tcollector-reporter.js
More details in:
https://github.com/thriftrw/thriftrw-node/pull/184
> Upgraded ThriftRW to include optimizations
