uber/tchannel-node

connection_base.js
in_request.js
operations.js
out_request.js
out_response.js
request.js
test/request-with-statsd.js
test/send.js
v2/handler.js

To future proof against v3 and lazy reqs.

Indirect access to cn header thru req.callerName

---

hyperbahn-client.js
package.json
peer.js

This is a follow-up for:
https://github.com/uber/hyperbahn/pull/3
Earlier the client changes the state to unadvertised once unadvertise call is made, without checking if the callback comes back successfully. This is because hyperbahn closes the peer and causes a connection reset error. That no longer happens because of graceful draining.
r: @Raynos @ShanniLi @jcorbin

Unadvertise should drain before close

---

test/as-json.js
test/as-thrift.js
test/request-with-statsd.js
test/response-stats.js
test/response-with-statsd.js
test/retry.js

I removed a bunch of `not ok` from the test blocks
and the asserts.
This makes ctrl+f "not ok" in travis 200% more effective
r: @jcorbin @kriskowal @shannili

confuse TAP less

---

channel.js
connection_base.js
operations.js
peer.js
test/chan_drain.js

So that we can re-use the existing draining/drainReason touch points for remote-triggered draining (ala #9).
r @Raynos

Make drain exemption invariant per channel

---

.travis.yml
package.json

Since 3.1.0 broke hyperbahn tests, and we didn't find out until too late.

Restore travis hyperbahn integration test

---

request.js
tcollector/reporter.js
test/timeouts.js

retryLimit, looking at the name, means max number of additional requests it should send. Current implementation takes initial request as first retry, and therefore is off by one.
After this fix, the behavior is:
0 no-retry (default)
1 retry once
2 retry twice
...
Fix hyperbahn as well:
https://github.com/uber/hyperbahn/pull/9
r: @Raynos @ShanniLi @jcorbin

Fix retryLimit off by one

---

connection.js
v2/handler.js

Prep before #15, which will continue work in `TChannelConnection#onErrorFrame`, and not always construct an error object. 
r @Raynos @rf

Pass error frames out of handler

---

connection.js
connection_base.js
test/chan_drain.js

When a connection starts draining, send a null-id'd declined error frame.
Note the message prefix is going to become a contract, since really this would be better off as a new frame type entirely; subsequent PR will branch essentially on "if the error has null id, and is declined, and the message starts with "draining:".
r @Raynos 
cc @blampe @prashantv @junchaowu

Add a draining "signal" frame

---

test/hyperbahn-client/constructor.js
test/hyperbahn-client/sub-channel.js
test/index.js

I accidentaly too #fierce the tests into hyperbahn repository.
This moves some of the tests back.

move hyperbahn-client tests back into tchannel-node

---

connection.js
relay_handler.js
test/index.js
test/relay_lazy.js

Passing a lazy-ported copy of tests/relay with only one logging assertion elided.

RelayHandler: add lazy support

---

peer.js
test/peer.js

When a peer has more than one connections, peer close always leaks one.
r: @Raynos @jcorbin @ShanniLi

Fix connection leak during peer close

---

docs/as-thrift.md
examples/as-thrift.js
examples/echo.thrift

This is what it takes to set up a service and client and do as/thrift now. Note that the peer has to be identified before a request. Thrift is more strict now. The Thrift method name would never have worked.
Fixes https://github.com/uber/tchannel/issues/1199

Update as/thrift example

---

hyperbahn-client.js
peer.js

This is tchannel part of change to stabilize unadvertise test.
1. unadvertise state change and event emit should wait for callback to succeed
2. removeConnectionEvent should emit along with conn, so the event listener can do sth
This change need be in before hyperbahn change:
https://github.com/uber/hyperbahn/pull/23
Multiple test runs passed
```bash
for i in {1..50}; do node unadvertise.js; done
```
r: @Raynos @ShanniLi

Stabilize unadvertise test part one

---

as/thrift.js
test/health.js

This refactors a bunch of code in AsThrift and adds a sync
helper that will deterministically load your meta thrift
file synchronously rather then asynchronously.
This fixes flappy BadRequests in the tests because of 
file IO & TCP IO race conditions.

Add a method to AsThrift to load Meta thrift synchronously

---

errors.js

The idea for this started with hyperbahn relay ad.  The intention is that this function can be used by an application to say "is this error exceptional?" to guide such things as error logging (vs downgrading to a warn, info, or just silencing).

Add errors.isFatal

---

relay_handler.js
test/relay-stats.js

We spend non-trivial CPU in the entire bufrw and net.Socket
layer converting call response into bytes.
We need to capture that in this stat
r: @rf @jcorbin @kriskowal

only emit relay.latency after writing bytes to socket

---

as/http.js

It turns out that request body can be larger than 1 mb, so remove the limit to avoid getting 413 error code
@vipulaneja  @jcorbin @ShanniLi

[as-http] Remove request body size limit

---

v2/error_response.js

This collection was only used by:
- the writeGuard to validate the outgoing code (only used for existence, string value irrelevant)
- `TChannelConnection#onErrorFrame` to log unhandled error frames; low impact, log field only
r @kriskowal

v2/error_response: fix CodeNames to use idiomatic strings

---

test/v2/lazy_frame.js
v2/call.js
v2/header.js

So that the upcoming stats path can get such things as the `cn` header.
r @Raynos @kriskowal 
Cheers @abhinav for making me think to use a typed array.

Add lazy v2 call header reading

---

in_request.js

This has caused multiple uncaught exception in production since yesterday. The property in question is redundant with a property by the same name added by connection.extendLogInfo, on the condition that a connection is affiliated with the request.

Fix uncaught exception on request without connection

---

channel.js
relay_handler.js
test/relay_lazy.js

Problem:
- we can turn lazy relaying on without incident
- but we cannot turn it off without a low defect rate
Why:
- lazy handling gets flipped only at the frame reading level currently
- however there are on going lazy requests at the time of flip off
- flipping immediately back to "eager only" frames breaks the ongoing handling of those requests
Solution:
cc @Raynos @kriskowal @rf

Add ability to toggle lazy relaying separately from lazy handling

---

relay_handler.js

By explicit branching and rarely calling `peer.waitForIdentified`.
r @Raynos @rf

Shorten path between LazyInReq and LazyOutReq

---

as/http.js
lib/stat.js
test/as-http.js

the stats added are:
tchannel.outbound.http-handler.request-build-latency: http request -> tchannel request
tchannel.outbound.http-handler.response-build-latency: tchannel response -> http response
tchannel.inbound.http-handler.request-build-latency: tchannel request -> http request
tchannel.inbound.http-handler.response-build-latency: http response -> tchannel response
tchannel.inbound.http-handler.service-call-latency: http request -> http response
stats are tagged by callerName, targetName, type (streamed/unstreamed).
r: @jcorbin @Raynos @ShanniLi 
cc: @davewhat @vipulaneja

[as-http] add http <=> tchannel request response build latency stats

---

relay_handler.js

Towards deferring observability reads until after frame relay:
- fixed a typo in a log
- added missing log context to said log
- defer counting the received call until after frame relay
- drop a `Date.now` call whose result wasn't used
- stop carrying headers on `LazyRelayInReq` as it holds a reference to the req frame buffer
r @rf @Raynos

Minor Cleanups in Lazy Relaying

---

v2/args.js

Out of #68:
- this length check wasn't just not needed...
- ...it's also potentially harmful since if the arg is long enough to overflow a frame, it will continue to not get chunked correctly
r @ShanniLi @Raynos

v2/args: fix subtlety in recent args string fix

---

v2/call.js
v2/cont.js

We forgot to unwrap the Result object which broke
all fragmented things in production.
r: @rf @jcorbin

& only works on numbers

---

test/lib/alloc-cluster.js

This allows parameterized test-suite runs, e.g.:
```
$ cat such_config.json
{
"choosePeerWithHeap": true
}
$ TCHANNEL_TEST_CONFIG=such_config.json node test
TAP version 13
ok 1 errors module is in sorted order
ok 2 Cancelled cases are in sorted order
ok 3 Declined cases are in sorted order
...
ok 2772 request() has response
ok 2773 response is ok
ok 2774 response body is 10
1..2774
```
To start iterating on the peer heap feature; a similar run can be done for lazy relaying.
r @Raynos

allocCluster: support TCHANNEL_TEST_CONFIG

---

channel.js

While chasing #31, I noticed that there was room for pre-mature callback out of `TChannel#close`.
r @abhinav

TChannel: ensure that close callback does not early fire

---

benchmarks/multi_bench.js

Benchmark improvements out of #31:
- client channel .listen/.close on the root channel
- better callback handling in test clients shutdown
r @Raynos @rf 
cc @benfleis

Better multi bench clients

---

connection.js
relay_handler.js
service-name-handler.js

r @jcorbin @Raynos 
Refactor `sendLazyErrorFrame` into one that takes `id` and `tracing` and one that takes a `reqFrame`

connection: refactor sendLazyErrorFrame into 2 methods

---

.travis.yml

Further test improvement observed on way to #31, to make hyperbahn integration failures more obvious from (maybe flap) fails of tchannel's own test sutie.

travis: vary the npm test script by env

---

hyperbahn_link_test.sh
package.json

Now supports:
- easy local run against existing hyperbahn checkout
- copies any $TCHANNEL_TEST_CONFIG to the destination hyperbahn to avoid ENOENT problem since `npm run ...` does a chdir to the destination dir
r @rf @abhinav

Better hyperbahn link test

---

benchmarks/index.js

This makes it easier to start a more non trivial hyperbahn relay
that blocks on ringpop joins

allow client start delay to be configurable

---

peer.js

Re-use the constructor closure instead.

TChannelPeer: drop closure around connection handling

---

channel.js
peers_base.js
root_peers.js

This makes it so that sanity sweeping cannot unboundedly block the event loop.

Limit sanity sweep

---

channel.js

causes unexpected test failure, needs tweaks.
test failure here:
https://github.com/uber/tchannel-node/issues/30#issuecomment-144597268

Assert against chan.listen() on sub-channels

---

channel.js
connection_base.js
out_request.js
peer.js
sub_peers.js
test/lib/barplot.js
test/lib/peer_score_obs.js
test/pool-of-servers.js

- add reason strings to all score invalidations
- peer score and choice observation events and test library
- optional hookup of new observation path in test/pool-of-servers
- optional bar plot the distribution in test/pool-of-servers

Add peer score debugging support, use it in test/pool-of-servers

---

as/thrift.js
package.json

- This change comes with a relaxation in ThriftRW to allow sets to be expressed as lists on the wire to ease migration where the old bug is present,
- Relaxed the requirement in TChannelAsThrift that application errors be instances of Error.
- Thrift exception instances are no longer Error instances. The specialization was unhelpful, complicated, and slow.

ThriftRW v2.5.1

---

connection_base.js

TChannelConnectionBase#onReqDone: fix mismatched v orphaned distinction

---

peer.js
test/chan_drain.js
test/index.js
test/peer_drain.js

A corollary of `chan.drain(reason, callback)` for initial use in hyperbahn's partial affinity peer reaping (towards https://github.com/uber/hyperbahn/pull/66).
r @Raynos

Add `peer.drain(reason, callback)`

---

peer.js
test/chan_drain.js
test/peer_drain.js

Previously we weren't calling drain on new incoming connections.

TChannelPeer: fix draining for incoming connections

---

peer.js
test/peer_drain.js

Trivial preps ahead of more `peer.drain` feature work.

Peer drain prep

---

peer.js
test/peer_drain.js

Especially check out the tests, they essentially implement the "N + 1 connection pruning" we want in hyperbahn; one test is server side prune, other test is client side prune.
r @rf @Raynos

Add directional support to `peer.drain`

---

benchmarks/multi_bench.js

The benchmark would abort way too early previously.
Not sure why this fixes it but I git bisected to unbreaking
the benchmark so #fierce

Fix benchmark by using self.callback

---

peer.js

Starting a new pattern of adding `#toString` and `#inspect` to our objects for easier debugging.
Makes it very easy to do things like `console.log(peers.toString())` for a short `TChannelPeer(X:Y), TChannelPeer(X1:Y2),...`.

Make TChannelPeer more easily inspectable

---

benchmarks/index.js

I suspect that we sometimes get flaps because 500ms simply is not
enough to start a thing.
Especially with the Hyperbahn worker which can take more then 500ms
before it listens to a port.
I've bumped the default delays to 1500ms to avoid the benchmarks
from flapping on us.

benchmarks: increase process startup delay to be more forgiving

---

v2/handler.js

A few fixes in here. The main one is to have one globally
shared WRITE_BUFFER.
To enable that I used a copy in the error path to allow the
globally shared buffer to be recycled instantly.
I also removed a little slice() because fff--- slice.

Optimize the v2/handler write() code.

---

peer.js

Not having the hostPort in prod makes this really hard to
debug.

better assertion message for peer exception

---

request.js
test/retry.js

We had a nice "feature" where we retried over connection
errors EXCEPT errors opening a new connection. 
This causes about 1/45 requests to fail in one of 
our production services because 1/45 hyperbahn hosts are
down.
r: @kriskowal @jcorbin @rf
cc: @blampe @prashantv Consider auditing python/go :)
cc: @MadanThangavelu This is the retry bugfix.

Actually retry on conn identification errors

---

channel.js
operations.js
peer.js

This should upper bound the number of tombstones in a process
I think long term we really should have the Operations data
structure be a LRU or some kind of fixed size upper bounded
data structure.
This should reduce GC pressure in hyperbahn

Add an upper bound to the lifetime of a tombstone

---

relay_handler.js

I removed a couple of call sites to `logError()` and replaced it
with more method calls.
Also got rid of a closure.

relay_handler: be more consistent about logging

---

relay_handler.js

We should add connection context to logging on the relay.
This will greatly aid debugging.

relay_handler: when logging add conneciton context

---

test/relay_lazy.js

This fixes a test flap. This test has non-deterministic
client or server timeouts.
By waiting 10ms the server is more likely to time out.

increase setTimeout to reduce flaps

---

connection.js
operations.js

This adds an extra logsite for any unknown error frames.
These generally occur in race conditions.

Add logging of unknown error frames.

---

errors.js
test/errors.js

I don't like refererring to `module.exports` within
functions.

Cleanup: refactor errors file for hygiene

---

relay_handler.js
test/relay_lazy.js

This fixes a bunch of test that didnt whitelist their logs.

Pre-emptive cleanup of lazy_relay test.

---

connection.js

This adds another log where we used to be silent.
This should help debug edge cases and this log actually triggers
in the draining test.

connection: Add a log for unknown call responses

---

request-handler.js

We completely swallowed errors when failing to parse args.
This is BAD (tm).

request-handler: emit error when failed to parse arg2/arg3

---

channel.js
root_peers.js

Not passing a callback causes a uncaught exception in production.

Ensure we always pass a callback to sanitySweep.

---

connection.js
errors.js
relay_handler.js
test/non-zero-ttl.js
v2/call.js
v2/handler.js
v2/lazy_frame.js

This change improves the relay code so that frame
parsing errors do not create errors.
- Adds tests for non-negative ttl aimed at servers
- Add an isParseError pattern to errors
- Mark InvalidTTL errors as parse errors
- Add logging to connection about unknown error frames
- Improve lazy relay by closing conn on protocol error

Downgrade an invalid ttl error to a warning

---

in_request.js

There is a lot of nuanced code here that I found whilst
trying to verify the semantics of timeouts against
the relay handler.
These commits make the code stabler and get rid of
some confusing logs, namely send response after timeout
and orphaned conn onReqDone

Improve the semantics of InRequest.onTimeout()

---

relay_handler.js

All these cleanups make it easier to move the lazy relay
into a seperate file.
These are mostly about having the same semantics for lazy &
eager in the RelayHandler itself.

Various lazy relay related cleanups.

---

lazy_relay.js
relay_handler.js
test/index.js
test/relay-clamps-the-ttl.js

We've had production problems where people accidentaly
set the time timeout to 1 million milliseconds (i.e. 16
minutes).
This change clamps the ttl to some sensible maximum for
safety reasons.

Clamp the maximum ttl in the relay.

---

drain.js
peer.js

Easy to accomodate now that we have the explicit `PeerDrain` object.  As
mentioned in early review for peer drain, we always wanted to have the ability
to say "and then ...".
This adds the two "and then ..."s that are used in Hyperbahn now/soon.
r @raynos @rf

Add goals to peer draining

---

as/http.js
test/as-http.js

We found a weird edgecase where we didnt send the response.
This fixes it by checking for the ended edgecase and sending
back the entire data.
r: @jcorbin @rf @Matt-Esch

Fix streaming bug in as/http

---

connection.js

Not doing so gives us a cyclic object that is being logged :(

Use tombstone.extendLogInfo() when logging tombstone.

---

out_request.js

Even if there is a response there is no garantuee that the
remote connection will ever send back an error frame or
continue frame for the out response especially if the in request
is timed out.
We need to just pop it right here

onTimeout always pop the out request.

---

connection.js
errors.js
lazy_relay.js
package.json

This gaurd will close the socket if we have too many
pending write operations.
This only happens if there is something wrong with the
socket; i.e. the uv_write call never calls the timeout
which we've seen in prod; something about the socket just
never calls the _write() callback.
I've checked a healthy 30% CPU worker and it only has two
pending WriteReq in memory; note that if libuv & stream_wrap
can flush the buffer synchrously then the cb to _write
gets called synchronously.
This should fix the memory leak we've seen in prod for the
last 24 hours.

Protect against TCP socket being full.

---

package.json
trace/span.js

The LCG lib was meant to be used for test fixtures only.
Towards #212 

Use xorshift to generate tracing ids

---

test/v2/lazy_frame.js
v2/lazy_frame.js

Line 105 will just throw if it's an invalid type, so the check for invalid type was ordered incorrectly.
The errors caused look like this:
```
TypeError: Cannot read property 'RW' of undefined
at BufferRW.readLazyFrameFrom [as readFrom] (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000101-v1/node_modules/hyperbahn/node_modules/tchannel/v2/lazy_frame.js:105:51)
at fromBufferResult (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000101-v1/node_modules/hyperbahn/node_modules/bufrw/interface.js:120:18)
at ReadMachine.seek (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000101-v1/node_modules/hyperbahn/node_modules/bufrw/stream/read_machine.js:116:15)
at ReadMachine.handleChunk (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000101-v1/node_modules/hyperbahn/node_modules/bufrw/stream/read_machine. …
```

v2/lazy_frame: fix check for valid frame type

---

errors.js

This is a simple improvement to the listen failed error to make debugging a tad easier.

Better listen failed error with host & port

---

as/thrift.js
package.json
test/health.js
test/hyperbahn-client/thrift-codec.js

Support entryPoint as well as source.
thriftSource and thriftFilename are no longer properties on tchannel-as-thrift. I don't think these should be exposed as apis. Any objection?

Support entryPoint in tchannel-as-thrift

---

channel.js
docs/channel.md
docs/host-port.md
docs/peer-to-peer.md
docs/sub-channels.md
host-port.js
peer.js
test/tchannel.js
v2/handler.js

This change introduces a `HostPort.validateX()` helper to allows consistent
validation of host & port concerns in all places we care.
I'll update this PR with actual markdown documentation real soon now.
@wolski asked us to clearly document what a `hostPort` actually means and
this consistent validation & documentation should help with that.
r: @rf @jcorbin

Validate host port consistently in listen(), connect(), init handshake

---

out_request.js

This fixes a bug where we reported latency on the
first call response frame instead of the last call
response frame.
This was naughty.
r: @kriskowal @rf @jcorbin

out_req: only mark end on last call response frame

---

operations.js

Because of nextTicks its possible for the cached `opKeys`
array and the `ops` object disagree about the state of the
world.
This is why I skip over any keys in `opKeys` that are not
own propertys of `ops`

Fix a race conditions in operations.sanitySweep()

---

as/thrift.js
request.js
test/as-thrift.js

Enabled application developers to hook into our shouldAppRetry
logic when doing thrift encoded stuff.
It's kind of hard to actually expose it "optimally" but at
least exposing a `parseException()` method allows people to
get the job done.
r: @jcorbin @kriskowal @malandrew

add TChannelThrift.parseException()

---

argstream.js
channel.js
lib/statsd.js
peer.js
root_peers.js
self_connection.js
self_peer.js
streaming_in_request.js
streaming_in_response.js
streaming_out_request.js
streaming_out_response.js
sub_peers.js
test/v2/args.js
trace/agent.js
trace/span.js
v2/args.js
v2/call.js
v2/cont.js
v2/handler.js
v2/header.js

- ArgStream
- BatchStatsd
- InArgStream
- OutArgStream
- StreamArg
- TChannel(Self)Peer
- TChannelSelfConnection
- TChannelV2Handler
- TChannel{Root,Sub}Peers
- v2/ArgsRW
- v2/HeaderRW
- all tracing classes in trace/{agent,span}.js
r @raynos @kriskowal

Drop new-less support from many internal classes

---

lazy_relay.js
peer.js

I've seen this uncaught in prod where `conn` is undefined.
Not really sure what to do here. for now its a logger.warn()
and No peer available.

handle case where there simply is no conn

---

channel.js

I accidentally evaluated `tchannel` in a REPL.
It spend 60 seconds printing the 200MB object with all
the peers & connections.
I added an inspect method to avoid accidentally evaluating
really really expensive objects.

add an inspect method to channel

---

v2/header.js

It turns out that typed arrays are not optimized.
This makes the code faster.

perf: use array instead of typed array

---

.eslintrc
benchmarks/micro/reading-important-fields.js
benchmarks/micro/reading-service-name-str.js
test/v2/lazy_frame.js
v2/call.js
v2/lazy_frame.js

This is a subset of https://github.com/uber/tchannel-node/pull/271
This only implements `readServiceStr()`; I've added a benchmark
for `readServiceStr()`.
It looks like the new implementation is about 2x faster, mostly
because:
- no allocations of `ReadResult()`
- using `utf8Slice()` directly.
I think @rf might be working on porting this fixes back
to `bufrw` itself; this will be great.

perf: Implement only readServiceStr()

---

benchmarks/micro/reading-caller-name-str.js
test/v2/lazy_frame.js
v2/call.js
v2/lazy_frame.js

This is a faster version of `readCallerNameStr()` for the lazy
path.
It's about 3x faster then the existing code.
- Avoid creating a slice() and use toString() directly
- Use faster toString() ( utf8Slice )
- Avoid creating Result objects.
r: @rf @jcorbin

Perf: Optimized readCallerNameStr() for lazy path

---

v2/args.js

This is required for TChannel to work with the zero-alloc bufrw.
r @Raynos @jcorbin

remember to inherit ArgRW from BufferRW

---

as/http.js
errors.js
test/as-http.js

node 0.10.42 started enforcing HTTP 1.1 more strictly
and says that a request must NOT have both a
Content-Length and a Chunked-Encoding header.
This caused an issue for us in the `as/http`
implementation since we forward incoming requests
to lb_pool. When we forward we take a the 
Chunked-Encoding header and pass it to lb_pool as well
as passing it a Buffer for the body.
lb_pool will set the Content-Length header and this
creates an issue for the HTTP parser on the other
end.
In reality the `forwardToLBPool()` method does buffering
of the incoming HTTP request and therefore must strip
the Chunked-Encoding header as it's no longer doing
Chunked-Encoding
r: @rf @jcorbin @kriskowal

Fix node 0.10.42 bug around Content-Length

---

channel.js
hyperbahn-client.js

We saw exception in case where the 'listening' was triggered after the tchannel is closed. Here is the fix for the race condition.

fix race conditions in tchannel and hyperbahn

---

lazy_relay.js
service-name-handler.js
test/lazy_conn_handler.js
test/lazy_handler.js
test/v2/call.js
test/v2/lazy_frame.js
v2/args.js
v2/call.js
v2/checksum.js
v2/cont.js
v2/error_response.js
v2/frame.js
v2/handler.js
v2/header.js
v2/init.js
v2/tracing.js

On the path to lazy zero-alloc. This removes many allocations at the bufrw layer.
It also gets us a few hundred ops/sec faster for the eager path:
Before
```
1:          PING,  1000/0 min/max/avg/p95:    9/ 352/ 154.68/ 265.55   3211ms total,  6228.59 ops/sec
1:          PING,  1000/0 min/max/avg/p95:   17/ 295/ 146.34/ 253.00   3001ms total,  6664.45 ops/sec
1:          PING,  1000/0 min/max/avg/p95:   21/ 287/ 141.63/ 241.00   2903ms total,  6889.42 ops/sec
1:          PING,  1000/0 min/max/avg/p95:   21/ 282/ 141.81/ 241.00   2908ms total,  6877.58 ops/sec
```
After
```
1:          PING,  1000/0 min/max/avg/p95:    9/ 322/ 143.92/ 246.55   2989ms total,  6691.20 ops/sec
1:          PING,  1000/0 min/max/avg/p95:   10/ 288/ 139.48/ 235.55   2852ms total,  7012.62 ops/sec
1: …
```

Less allocations

---

lazy_relay.js
peer.js
test/relay_lazy.js

Adds a method called `stopWaitingForIdentified` on peers. Uses a descriptor table to keep track of what needs to be released.
Note that there is a `free` added to the end of `LazyRelayInReq#onError`. This `free` would cause test failures but for the `stopWaitingForIdentified` method and its use in `LazyRelayInReq#clear`, hence the lack of tests; this condition is already sufficiently stressed.
This `free` added to the bottom of `onError` is (at least one of) the missing `free`s that are causing the object pool to not reuse objects right now in prod.
r @jcorbin @Raynos

add stopWaitingForIdentified and use in LazyRelayInreq

---

channel.js
lib/object_pool.js
relay_handler.js
test/lib/alloc-cluster.js

Adds a verification step when tearing down a test cluster that ensures that all objects allocated using pools have been freed.
Adds a missing `LazyRelayInReq#free` upon no peer available.
Builds on #300 because they both modify the ObjectPool singelton.
r @raynos @jcorbin

Free LazyRelayInReqs upon NoPeerAvailable; Object Pool verification

---

channel.js
lib/object_pool.js
relay_handler.js
stat-tags.js
test/lib/alloc-cluster.js
test/object_pool.js

Use batch stats in object pool. We don't actually pass a statsd to TChannel in Hyperbahn, so we have to use the batch statsd.
r @jcorbin @Raynos

ObjectPool: use batch stats

---

channel.js

This change makes the peer heap the default in the
tchannel library. This means all users of tchannel
will go fast by default.

channel: default choose peer with heap to true

---

lazy_relay.js

It might be possible for the same `inreq` to fail in multiple
ways in one tick of the event loop.
This means that other failures could free the inreq and it would
be gone.
Once we get to the nextTick we should do a best effort error
handling and if it's already freed assume that it failed with
a different but related error.

Shield againts calling `onError()` on null.

---

lazy_relay.js
peer.js

There is a free() somewhere that isnt doing the right
thing. Freed objects are sticking around in pending
operations on the connection.
This causes a bunch of bugs with trying to error or
timeout a freed LazyOutReq/LazyInReq
I've added defense in depth to work around these
issues.

Fix a bunch of uncaught exceptions.

---

benchmarks/Makefile
benchmarks/index.js
benchmarks/multi_bench.js
package.json
peer.js
peer_heap.js
sub_peers.js
test/index.js
test/lib/alloc-cluster.js
test/lib/batch-client.js
test/peer-to-peer-load-balance.js

I've written a test to verify load balance distribution
between client & server in p2p mode.
As can be seen, without minConnections the load distribution
is absolutely terrible and it improves with minConnections

Implement minConnections as a step towards goalConnections

---

peer.js
peer_heap.js
sub_peers.js
test/peer-to-peer-load-balance.js

There is an edge cases where the peer selection logic as
part of `minConnections` might try and open a lot of connections.
This can be quite expensive in terms of CPU & logging.
This change adds exponential backoff to trying to open a connection
on an unconnected peer when we have less connected peers then
minConnections.
There might be a scenario where you have minConnections: 4 and
numPeers: 5, except two of 5 peers are down. In that scenario
tchannel would try and open a lot of connections to the down
peers even though it should know that they are down.
The more general solution to this is remember whether a peer
is healthy or not.

peer: add tryConnect() with backoff

---

lazy_relay.js
v2/call.js

There is a bug where we read the resp flags, not the resp code.
This means our `app-error` stat is really a fragmentation stat
and not a thrift exception stat.
r: @kriskowal @jcorbin @blampe

lazy_relay: read res code, not res flags

---

package.json

`ansi-color` doesn't need to be there - nothing used in the module itself uses it. Noticed it when looking through dependencies and saw that `chalk` was being used instead.

Remove ansi-color from devDependencies

---

lazy_relay.js

Observed an uncaught exception following this guard. Maybe we should fix the object pool.
r @raynos @jcorbin

Work around problem with sendErrorFrame on reset lazy relay

---

as/thrift.js
package.json

I’ve added a flag to the latest version of ThriftRW that allows users to opt-in for semantics regarding unmarked (not optional, not required) fields of argument structs that is consistent with the other ThriftRWs. We have lost the battle for required-only arguments. With the new semantics, arguments are optional by default and and you can opt-in for required.
r @jcorbin @Raynos

Thread allowOptionalArguments through Thrift

---

as/json.js
as/thrift.js
test/as-json.js
test/as-thrift.js

`baseAppHeaders` allow us to specify some app headers in the call to `request`.

support baseAppHeaders in as/json and as/thrift

---

lazy_relay.js

r @raynos @kriskowal
Just adding a guard so this doesn't keep causing uncaughts and alerting

Add free guard to LazyRelayInReq#onTimeout

---

in_request.js
out_request.js

We've had an issue with the `rt-msg` service in production
where they were seeing multi-minute latencies, probably
because the timeout measure the time until the first call
response frame, not the last.
We had previously supported streaming by making the timeout
behave until the first call response frame.
However, this causes issues for people that encounter
fragmented call responses.
Since we have barely any streaming customers we should
recommend that people who use streaming and want timeout
until first response frame simply set a very large timeout
and a secondary custom timeout until the first response.
r: @ssyang @jcorbin @kriskowal

timeout should hold until last byte

---

channel.js
test/tchannel.js

@Raynos suggested to do this so we don't have to import the tchannel dependency into our libs repo @syyang  @charliezhang

add a isUnhealthyError method into TChannel used for client-side throttling

---

service-name-handler.js

This allows us to make `isBusy()` decisions based
on InRequest information.
r: @rf

pass req through to `isBusy()`

---

channel.js
peer.js
sub_peers.js
test/peer-to-peer-load-balance.js

It looks like in production we backoff far too aggressively.
This is caused by having multiple concurrent `tryConnect()` attempts
which will all "succeed" or "fail" and thus apply the doubling
logic many times ballooning the retry attempt delay.
I've also added a hard gap of 30s backoff so every 30s we will
try to open the connection.
r: @syyang

Improve the connection backoff logic.

---

benchmarks/Makefile
benchmarks/bench_server.js
benchmarks/index.js
benchmarks/multi_bench.js
benchmarks/relay_server.js
benchmarks/trace_server.js

The Makefile is not configured to work out of the box.
There was also one bug in the benchmark bootstrapper that
caused the tracing benchmark to fail
I've also turned on 100% trace reporting instead of 1% for the
tracing benchmark...
So currently when benchmarking wrt to tracing:
- `make take` will benchmark p2p, with span creation and noop-reporter
- `make take_relay` will benchmark with relay, with span creation & noop-reporter
- `make trace` will benchmark with relay, with span creation & 100% reporter
The four modes do the following on my laptop,
- 6.5k @ `make take`, hand-edited to have trace: false, aka no span creation
- 5k @ `make take`, normal, span creation, noop reporter
- 3k @ `make take_relay`, normal, span creation, relay, noop reporter
- 1k @ `make take_trace`, normal, span …

Fixup benchmarks Makefile to work out of box.

---

channel.js
peer-file-watcher.js
test/peer-file-watcher.js

Moving `updatePeer` and `drainPeer` up to `TChannel` level so we can update without using peer file watcher.

Move updatePeer and drainPeer up to TChannel level

---

connection.js
peer.js
request.js
sub_peers.js
test/relay-to-dead.js
test/timeouts.js

We need to do another checkTimeout() after the request
is identified to double check that we did not consume our
request budget in the connection init handshake.
We also need to update the `elapsed` time so that when we
make our outbound request we set a proper `ttl-elapsed` timeout
on the per attempt request.
r: @zhijin @syyang

request: checkTimeout() after identified

---

channel.js

There is an edge case where a server connection closes in
the middle of a sanity sweep. This would cause an uncaught
as that connection cannot be sweeped.
If the connection doesn't exist we just move along to the next
step in sanity sweep.
r: @rf @ssyang

handle edge case where there is no connection

---

request.js
test/timeouts.js

This improves the pre-flight waitForIdentified() logic
in the tchannel.Request class.
Here we will actually do a check to see if we have
a usable connection and skip the waiting.
If we have to wait because there are zero connections
we also allocate a RequestOperation with a properly
configured timeout and add it to the timeHeap.
This means that the request will timeout within it's
specified `timeout` irregardless of what the connection
initTimeout value is.
We clean up and cancel the timeout once a connection
is identified and available
r: @zhijin @syyang

ensure that requests timeout even when initOp

---

peer.js

Because of edge cases there is a race between connection
identification and timeouts.
A timeout may still fire whilst a connection has already
been estabilished.
We need a null check here and do a no-op.
r: @zhijinli @proflayton

peer: handle edge case where identified descriptor is null

---

CHANGELOG.md
peer_score_strategies.js
test/peer-file-watcher.js
test/peer-to-peer-load-balance.js
test/pool-of-servers.js
test/relay-kills-socket-after-timeouts.js

This updates the peer selection score strategy to mark
unconnected peers as the lowest score.
This means that we will not fully connect and will
in general use 1 peer most of the time.
The only time more then 1 peer is used per sub channel:
- minConnections is configured for p2p
- hyperbahn is used and extra inbound peers are estabilished.
r: @kriskowal @prashantv @jialiehu

Updated peer score strategy to not fully connect

---

as/thrift.js
package.json
test/as-thrift.js

There was logic that attempted to retrieve the set exception from the method response struct. However, it made the assumption that the default value would always be null. In this case, with undefined as the default value, the user would get returned any of the error values (leading sometimes to undefined error responses).
Accept null or undefined values on the response structs. Ideally we should treat the the exception response as a union and have some convenience methods to fetch the value

Handle undefined as default value in thrift result structs

---

.travis.yml
package.json
scripts/postinstall.sh

This change removes the postinstall hook and replaces it with express dependencies on farmhash and sse4-crc32. This change targets the v3 release train and will not land on master.

Expressly depend on binary dependencies

---

channel.js

Currently sub-channel depends on the global time-heap and this will increase the min-heap array size which is used to track the timers. In order to reduce the min heap array size, sub-channel can pass down the timeHeap from the opts.

Enable timeHeap configuration.
